In [1]:
#Importing important libraries.
import numpy as np
import pandas as pd
import nltk
from string import punctuation
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [2]:
nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to
[nltk_data]    |     C:\Users\Swastik\AppData\Roaming\nltk_data...
[nltk_data]    |   Package abc is already up-to-date!
[nltk_data]    | Downloading package alpino to
[nltk_data]    |     C:\Users\Swastik\AppData\Roaming\nltk_data...
[nltk_data]    |   Package alpino is already up-to-date!
[nltk_data]    | Downloading package biocreative_ppi to
[nltk_data]    |     C:\Users\Swastik\AppData\Roaming\nltk_data...
[nltk_data]    |   Package biocreative_ppi is already up-to-date!
[nltk_data]    | Downloading package brown to
[nltk_data]    |     C:\Users\Swastik\AppData\Roaming\nltk_data...
[nltk_data]    |   Package brown is already up-to-date!
[nltk_data]    | Downloading package brown_tei to
[nltk_data]    |     C:\Users\Swastik\AppData\Roaming\nltk_data...
[nltk_data]    |   Package brown_tei is already up-to-date!
[nltk_data]    | Downloading package cess_cat to
[nltk_data]    |     

[nltk_data]    |   Package stopwords is already up-to-date!
[nltk_data]    | Downloading package subjectivity to
[nltk_data]    |     C:\Users\Swastik\AppData\Roaming\nltk_data...
[nltk_data]    |   Package subjectivity is already up-to-date!
[nltk_data]    | Downloading package swadesh to
[nltk_data]    |     C:\Users\Swastik\AppData\Roaming\nltk_data...
[nltk_data]    |   Package swadesh is already up-to-date!
[nltk_data]    | Downloading package switchboard to
[nltk_data]    |     C:\Users\Swastik\AppData\Roaming\nltk_data...
[nltk_data]    |   Package switchboard is already up-to-date!
[nltk_data]    | Downloading package timit to
[nltk_data]    |     C:\Users\Swastik\AppData\Roaming\nltk_data...
[nltk_data]    |   Package timit is already up-to-date!
[nltk_data]    | Downloading package toolbox to
[nltk_data]    |     C:\Users\Swastik\AppData\Roaming\nltk_data...
[nltk_data]    |   Package toolbox is already up-to-date!
[nltk_data]    | Downloading package treebank to
[nltk_data] 

True

In [3]:
#Sample Document
doc1 = "This is a very good and plain paper. this is really \
good and interesting"
doc2 = "This paper is very interesting, awesome."

In [4]:
#function for cleaning the raw data.
def clean_txt(sent):
    tokens = word_tokenize(sent.lower())                                                              # converting all words into lower case.
    stop_updated = stopwords.words("english") + list(punctuation)                                     # creating list of stopword and punctuations.
    final_word = [term for term in tokens if term not in stop_updated 
               and len(term) > 2]                                                    #filtering out all the stopwords and punctuation and len of words should be greater than 2. 
    res = " ".join(final_word)                                                                        # joining all words converting list to string.
    return res                                                                                        #returning final clean documnent.

In [5]:
#cleaning doc1
doc1_clean = clean_txt(doc1)
doc1_clean

'good plain paper really good interesting'

In [6]:
#cleaning doc2
doc2_clean = clean_txt(doc2)
doc2_clean

'paper interesting awesome'

In [7]:
#creating the dataframe from all the document.
doc = pd.DataFrame([doc1_clean, doc2_clean], columns=["text"])
doc

text
0  good plain paper really good interesting
1                 paper interesting awesome

## Count Vectors
- In countVectorizer, the documents will be reprsented by the number of time each word appears in the document.

In [8]:
from sklearn.feature_extraction.text import CountVectorizer

In [9]:
count_vect=CountVectorizer()

In [10]:
X=count_vect.fit_transform(doc['text'])
X

<2x6 sparse matrix of type '<class 'numpy.int64'>'
	with 8 stored elements in Compressed Sparse Row format>

- Fit -> Extract distinct words to form a bag of words.

- Transform - Compute the occurrence of every word from the BOW in each document.

In [11]:
#obtaining the BOW's
count_vect.get_feature_names()

['awesome', 'good', 'interesting', 'paper', 'plain', 'really']

In [12]:
#Get the position of every word in the BOW
print(count_vect.vocabulary_)

{'good': 1, 'plain': 4, 'paper': 3, 'really': 5, 'interesting': 2, 'awesome': 0}


In [13]:
#converting sparse matrix of count vectorizer into array.
X.toarray()

array([[0, 2, 1, 1, 1, 1],
       [1, 0, 1, 1, 0, 0]], dtype=int64)

In [14]:
DTM=pd.DataFrame(X.toarray(),columns=count_vect.get_feature_names())
DTM

awesome  good  interesting  paper  plain  really
0        0     2            1      1      1       1
1        1     0            1      1      0       0

- We can see the occurrence of each word in each document.

#### Creating Bigrams - Bigrmas are words taken in pairs. The next immediate word is grouped with the current word to form a bigram

* Unigrams- one word
* Bigram- two words
* Trigram- three words

Any combination of the above can be created

### Bigram

In [15]:
# A token is called as a bigram if its min and max length is 2
count_vect_bg=CountVectorizer(ngram_range=(2,2)) 

In [16]:
X_bg=count_vect_bg.fit_transform(doc['text'])

In [17]:
doc

text
0  good plain paper really good interesting
1                 paper interesting awesome

In [18]:
print(count_vect_bg.get_feature_names())

['good interesting', 'good plain', 'interesting awesome', 'paper interesting', 'paper really', 'plain paper', 'really good']


In [19]:
DTM_bg=pd.DataFrame(X_bg.toarray(),columns=count_vect_bg.get_feature_names())

In [20]:
DTM_bg

good interesting  good plain  interesting awesome  paper interesting  \
0                 1           1                    0                  0   
1                 0           0                    1                  1   

   paper really  plain paper  really good  
0             1            1            1  
1             0            0            0

In [21]:
count_vect_ubg=CountVectorizer(ngram_range=(1,2))                                                   #ngram_range(1,2) create uni and bi gram both.

X_ubg=count_vect_ubg.fit_transform(doc['text'])

print(count_vect_ubg.get_feature_names())

DTM_ubg=pd.DataFrame(X_ubg.toarray(),columns=count_vect_ubg.get_feature_names())

DTM_ubg

['awesome', 'good', 'good interesting', 'good plain', 'interesting', 'interesting awesome', 'paper', 'paper interesting', 'paper really', 'plain', 'plain paper', 'really', 'really good']


awesome  good  good interesting  good plain  interesting  \
0        0     2                 1           1            1   
1        1     0                 0           0            1   

   interesting awesome  paper  paper interesting  paper really  plain  \
0                    0      1                  0             1      1   
1                    1      1                  1             0      0   

   plain paper  really  really good  
0            1       1            1  
1            0       0            0

### Trigram

In [22]:
# A token is called a trigram if its min and max length is 3
count_vect_tbg=CountVectorizer(ngram_range=(3,3))

X_tbg=count_vect_tbg.fit_transform(doc['text'])

print(count_vect_tbg.get_feature_names())

DTM_tbg=pd.DataFrame(X_tbg.toarray(),columns=count_vect_tbg.get_feature_names())

DTM_tbg

['good plain paper', 'paper interesting awesome', 'paper really good', 'plain paper really', 'really good interesting']


good plain paper  paper interesting awesome  paper really good  \
0                 1                          0                  1   
1                 0                          1                  0   

   plain paper really  really good interesting  
0                   1                        1  
1                   0                        0

In [23]:
# Get only top n features in our DTM
count_nfetures=CountVectorizer(max_features=3)
count_nfetures
X_nfeatures=count_nfetures.fit_transform(doc['text'])
count_nfetures.get_feature_names()

['good', 'interesting', 'paper']

In [24]:
DTM_nfeatures=pd.DataFrame(X_nfeatures.toarray(),columns=count_nfetures.get_feature_names())
DTM_nfeatures

good  interesting  paper
0     2            1      1
1     0            1      1

In [25]:
#creating countvectors on datasets.
imdb=pd.read_csv('imdb_sentiment.csv')
imdb.head()

review  sentiment
0  A very, very, very slow-moving, aimless movie ...          0
1  Not sure who was more lost - the flat characte...          0
2  Attempting artiness with black & white and cle...          0
3       Very little music or anything to speak of.            0
4  The best scene in the movie was when Gerardo i...          1

In [26]:
#cleaning the review column.
imdb['clean']=imdb['review'].apply(lambda x: clean_txt(x))
imdb.head()

review  sentiment  \
0  A very, very, very slow-moving, aimless movie ...          0   
1  Not sure who was more lost - the flat characte...          0   
2  Attempting artiness with black & white and cle...          0   
3       Very little music or anything to speak of.            0   
4  The best scene in the movie was when Gerardo i...          1   

                                               clean  
0  slow-moving aimless movie distressed drifting ...  
1  sure lost flat characters audience nearly half...  
2  attempting artiness black white clever camera ...  
3                        little music anything speak  
4  best scene movie gerardo trying find song keep...

In [27]:
#creating count vector for review in the imdb dataset.
count_vect_tbg=CountVectorizer(ngram_range=(1,2))

X_tbg=count_vect_tbg.fit_transform(imdb['clean'])

DTM_tbg=pd.DataFrame(X_tbg.toarray(),columns=count_vect_tbg.get_feature_names())

DTM_tbg.head()

10  10 10  10 grade  10 scale  10 score  10 setting  13  13 film  \
0   0      0         0         0         0           0   0        0   
1   0      0         0         0         0           0   0        0   
2   0      0         0         0         0           0   0        0   
3   0      0         0         0         0           0   0        0   
4   0      0         0         0         0           0   0        0   

   13 rating  15pm  ...  youtube  yun  yun fat  zillion  zillion times  \
0          0     0  ...        0    0        0        0              0   
1          0     0  ...        0    0        0        0              0   
2          0     0  ...        0    0        0        0              0   
3          0     0  ...        0    0        0        0              0   
4          0     0  ...        0    0        0        0              0   

   zombie  zombie movies  zombie students  zombiez  zombiez part  
0       0              0                0        0             0  
1       0              0                0        0             0  
2       0              0                0        0             0  
3       0              0                0        0             0  
4       0              0                0        0             0  

[5 rows x 9226 columns]

### TF-IDF Vectors.
- It measure the importance of a word to a document in corpus.The importance of a word increases proportionally to the number of times a word appears in the document but is reduced by the frequency of the word present in the corpus.

In [28]:
#Using sckit learn feature extraction module.
from sklearn.feature_extraction.text import TfidfVectorizer

In [29]:
#here also we can create bigram, trigram using ngram_range.
tfidf_vct=TfidfVectorizer()

In [30]:
#fitting and transforming the document on the tf-idf.
X=tfidf_vct.fit_transform(doc['text'])

In [31]:
#converting matrix to dataframe.
tfidf=pd.DataFrame(X.toarray(),columns=tfidf_vct.get_feature_names())
tfidf

awesome      good  interesting     paper     plain    really
0  0.000000  0.755256     0.268685  0.268685  0.377628  0.377628
1  0.704909  0.000000     0.501549  0.501549  0.000000  0.000000

In [32]:
# Get only top n features in our tfidf
tfidf_nfetures=TfidfVectorizer(max_features=3)
tfidf_nfetures
X_nfeatures=tfidf_nfetures.fit_transform(doc['text'])
tfidf_nfetures.get_feature_names()

['good', 'interesting', 'paper']

In [33]:
#creating tfidf vector for review in the imdb dataset.
tfidf_vect_tbg=TfidfVectorizer(ngram_range=(1,2))

X_tbg=tfidf_vect_tbg.fit(imdb['clean']) #fitting the data.
y_tbg=tfidf_vect_tbg.transform(imdb['clean']) #transforming the data.
#Matrix to dataframe
DTM_tbg=pd.DataFrame(y_tbg.toarray(),columns=tfidf_vect_tbg.get_feature_names())

DTM_tbg.tail()

10  10 10  10 grade  10 scale  10 score  10 setting   13  13 film  \
743  0.0    0.0       0.0       0.0       0.0         0.0  0.0      0.0   
744  0.0    0.0       0.0       0.0       0.0         0.0  0.0      0.0   
745  0.0    0.0       0.0       0.0       0.0         0.0  0.0      0.0   
746  0.0    0.0       0.0       0.0       0.0         0.0  0.0      0.0   
747  0.0    0.0       0.0       0.0       0.0         0.0  0.0      0.0   

     13 rating  15pm  ...  youtube  yun  yun fat  zillion  zillion times  \
743        0.0   0.0  ...      0.0  0.0      0.0      0.0            0.0   
744        0.0   0.0  ...      0.0  0.0      0.0      0.0            0.0   
745        0.0   0.0  ...      0.0  0.0      0.0      0.0            0.0   
746        0.0   0.0  ...      0.0  0.0      0.0      0.0            0.0   
747        0.0   0.0  ...      0.0  0.0      0.0      0.0            0.0   

     zombie  zombie movies  zombie students  zombiez  zombiez part  
743     0.0            0.0              0.0      0.0           0.0  
744     0.0            0.0              0.0      0.0           0.0  
745     0.0            0.0              0.0      0.0           0.0  
746     0.0            0.0              0.0      0.0           0.0  
747     0.0            0.0              0.0      0.0           0.0  

[5 rows x 9226 columns]

In [34]:
#finding top 10 keywords for each reviews based on tfidf
top_key_words=[]
for i in range(imdb.shape[0]):
    #np.take array and indices and return the array at that indices.
    top_key_words.append(np.take(X_tbg.get_feature_names(), y_tbg.toarray()[i].argsort()[::-1][:10])) #sorting the value and extracting top 10 feature.

In [35]:
imdb['KeyWords']=top_key_words

In [36]:
imdb.head()

review  sentiment  \
0  A very, very, very slow-moving, aimless movie ...          0   
1  Not sure who was more lost - the flat characte...          0   
2  Attempting artiness with black & white and cle...          0   
3       Very little music or anything to speak of.            0   
4  The best scene in the movie was when Gerardo i...          1   

                                               clean  \
0  slow-moving aimless movie distressed drifting ...   
1  sure lost flat characters audience nearly half...   
2  attempting artiness black white clever camera ...   
3                        little music anything speak   
4  best scene movie gerardo trying find song keep...   

                                            KeyWords  
0  [movie distressed, young man, drifting, aimles...  
1  [lost flat, nearly, sure lost, flat characters...  
2  [became even, almost non, artiness black, arti...  
3  [little music, music anything, anything speak,...  
4  [find song, trying find, running head, song ke...

### Text Classification Model using TF-IDF Vector.
- About DataSet: Dataset Contains reviews of different movies and its sentiment score.
- Review is the predictor Variable and Sentiment is the target variable. Model is to classify whetherbthe given review has postive or negative sentiments.
- 0 for Negative Sentiment,1 for Positive Sentiment.

In [37]:
#splitting feature and target variable.
X=imdb['clean']
y=imdb['sentiment']

#splitting the data into train and test set.
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,y,test_size=0.20)

# Create a tfidf vector for input to the model.
from sklearn.feature_extraction.text import TfidfVectorizer

#creating the tfidf vector till bigram.
tfidf_vect=TfidfVectorizer(ngram_range=(1,2))

#Extract the features on the reviews for train -fit
#Compute the count of every word extracted in every document(review)
X_train_bow=tfidf_vect.fit_transform(X_train)

#For all the features extracted, compute the count 
# in the test data set of reviews
X_test_bow=tfidf_vect.transform(X_test)


## fit(): Fit the vectorizer/model to the training data and save the vectorizer/model to a variable (returns sklearn.feature_extraction.text.TfidfVectorizer)

## transform(): Use the variable output from fit() to transformer validation/test data (returns scipy.sparse.csr.csr_matrix)

## fit_transform(): Sometimes you to directly transform the training data, so you use fit() + transform() together, thus fit_transform(). (returns scipy.sparse.csr.csr_matrix)

#Using logistic regression to classify the sentiment.
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train_bow, Y_train)

#predicting the class for the test set.
y_pred = classifier.predict(X_test_bow)

# performance metrics.
from sklearn.metrics import accuracy_score, confusion_matrix


print('Accuracy Socre of Logistic Regression Model is {}'.format(accuracy_score(Y_test,y_pred)))

confusion_matrix(Y_test,y_pred)

Accuracy Socre of Logistic Regression Model is 0.8


array([[44, 26],
       [ 4, 76]], dtype=int64)

In [ ]:
# #splitting feature and target variable.
# X=imdb['clean']
# y=imdb['sentiment']

# #splitting the data into train and test set.
# from sklearn.model_selection import train_test_split
# X_train,X_test,Y_train,Y_test=train_test_split(X,y,test_size=0.20)

# # Create a tfidf vector for input to the model.
# from sklearn.feature_extraction.text import TfidfVectorizer

# #creating the tfidf vector till bigram.
# tfidf_vect=TfidfVectorizer(ngram_range=(1,2))

# #Extract the features on the reviews for train -fit
# #Compute the count of every word extracted in every document(review)
# X_train_bow=tfidf_vect.fit_transform(X_train)

# #For all the feature extracted, compute the count 
# # in the test data set of reviews
# X_test_bow=tfidf_vect.transform(X_test)

# #Using logistic regression to classify the sentiment.
# from sklearn.svm import SVC
# classifier = SVC()
# classifier.fit(X_train_bow, Y_train)

# #predicting the class for the test set.
# y_pred = classifier.predict(X_test_bow)

# # performance metrics.
# from sklearn.metrics import accuracy_score, confusion_matrix

# print('Accuracy Socre of SVC Model is {}'.format(accuracy_score(Y_test,y_pred)))

# confusion_matrix(Y_test,y_pred)

Accuracy Socre of SVC Model is 0.7733333333333333


array([[45, 14],
       [20, 71]], dtype=int64)

### Cosine Similarity 

Cosine similarity is a metric used to determine how similar the documents are irrespective of their size.

Mathematically, it measures the cosine of the angle between two vectors projected in a multi-dimensional space. 
This metric is a measurement of orientation and not magnitude.

The two vectors are arrays containing the word counts of two documents.

The cosine similarity is advantageous because even if the two similar documents are far apart by the Euclidean distance because of the size (like, the word 'cricket' appeared 50 times in one document and 10 times in another) they could still have a smaller angle between them.

Smaller the angle, higher the similarity.

Two documents are similar if all the words are same in both the documents.

In [38]:
doc_trump = "Mr. Trump became president after winning the political election. \
Though he lost the support of some republican friends, Trump is friends with President Putin"

doc_election = "President Trump says Putin had no political interference in the election outcome.\
He says it was a witchhunt by political parties. \
He claimed President Putin is a friend who had nothing to do with the election"

doc_putin = "Post elections, Vladimir Putin became President of Russia.\
President Putin had served as the Prime Minister earlier in his political career"

In [39]:
documents=[doc_trump,doc_putin,doc_election]

In [40]:
tfidf_vect=TfidfVectorizer(ngram_range=(1,1),stop_words='english')
X=tfidf_vect.fit_transform(documents)

In [41]:
df=pd.DataFrame(X.toarray(),columns=tfidf_vect.get_feature_names(),
               index=['doc_trump','doc_putin','doc_election'])
df

career   claimed   earlier  election  elections    friend  \
doc_trump     0.000000  0.000000  0.000000  0.203368   0.000000  0.000000   
doc_putin     0.287012  0.000000  0.287012  0.000000   0.287012  0.000000   
doc_election  0.000000  0.241982  0.000000  0.368067   0.000000  0.241982   

              friends  interference      lost  minister  ...     putin  \
doc_trump     0.53481      0.000000  0.267405  0.000000  ...  0.157934   
doc_putin     0.00000      0.000000  0.000000  0.287012  ...  0.339028   
doc_election  0.00000      0.241982  0.000000  0.000000  ...  0.285837   

              republican    russia      says    served   support     trump  \
doc_trump       0.267405  0.000000  0.000000  0.000000  0.267405  0.406737   
doc_putin       0.000000  0.287012  0.000000  0.287012  0.000000  0.000000   
doc_election    0.000000  0.000000  0.483963  0.000000  0.000000  0.184033   

              vladimir   winning  witchhunt  
doc_trump     0.000000  0.267405   0.000000  
doc_putin     0.287012  0.000000   0.000000  
doc_election  0.000000  0.000000   0.241982  

[3 rows x 27 columns]

In [42]:
from sklearn.metrics.pairwise import cosine_similarity

In [43]:
#Obtain the similarity between every document
# result is a nXn matrix where n is the no. of documents
cs_docs=cosine_similarity(df)
cs_docs

array([[1.        , 0.18740386, 0.33027897],
       [0.18740386, 1.        , 0.24226661],
       [0.33027897, 0.24226661, 1.        ]])

In [44]:
# find the similarity between first document and the third document
cosine_similarity(df[0:1],df[1:2])

array([[0.18740386]])

In [45]:
#sorting the document based on similarity score.
ind=int(cs_docs[0].argsort()[::-1][1:2])
print("Document which is very close to doc0 is:",df.index[ind])

Document which is very close to doc0 is: doc_election


In [46]:
#Similarly we use for the imdb dataset to find the most similar reviwes.
#creating the tfidf vector till bigram.
tfidf_vect=TfidfVectorizer(ngram_range=(1,2))

#Extract the features on the reviews for train -fit
#Compute the count of every word extracted in every document(review)
tfidf_bow=tfidf_vect.fit_transform(imdb['clean'])

In [47]:
df=pd.DataFrame(tfidf_bow.toarray(),columns=tfidf_vect.get_feature_names())
df

10  10 10  10 grade  10 scale  10 score  10 setting   13  13 film  \
0    0.0    0.0       0.0       0.0       0.0         0.0  0.0      0.0   
1    0.0    0.0       0.0       0.0       0.0         0.0  0.0      0.0   
2    0.0    0.0       0.0       0.0       0.0         0.0  0.0      0.0   
3    0.0    0.0       0.0       0.0       0.0         0.0  0.0      0.0   
4    0.0    0.0       0.0       0.0       0.0         0.0  0.0      0.0   
..   ...    ...       ...       ...       ...         ...  ...      ...   
743  0.0    0.0       0.0       0.0       0.0         0.0  0.0      0.0   
744  0.0    0.0       0.0       0.0       0.0         0.0  0.0      0.0   
745  0.0    0.0       0.0       0.0       0.0         0.0  0.0      0.0   
746  0.0    0.0       0.0       0.0       0.0         0.0  0.0      0.0   
747  0.0    0.0       0.0       0.0       0.0         0.0  0.0      0.0   

     13 rating  15pm  ...  youtube  yun  yun fat  zillion  zillion times  \
0          0.0   0.0  ...      0.0  0.0      0.0      0.0            0.0   
1          0.0   0.0  ...      0.0  0.0      0.0      0.0            0.0   
2          0.0   0.0  ...      0.0  0.0      0.0      0.0            0.0   
3          0.0   0.0  ...      0.0  0.0      0.0      0.0            0.0   
4          0.0   0.0  ...      0.0  0.0      0.0      0.0            0.0   
..         ...   ...  ...      ...  ...      ...      ...            ...   
743        0.0   0.0  ...      0.0  0.0      0.0      0.0            0.0   
744        0.0   0.0  ...      0.0  0.0      0.0      0.0            0.0   
745        0.0   0.0  ...      0.0  0.0      0.0      0.0            0.0   
746        0.0   0.0  ...      0.0  0.0      0.0      0.0            0.0   
747        0.0   0.0  ...      0.0  0.0      0.0      0.0            0.0   

     zombie  zombie movies  zombie students  zombiez  zombiez part  
0       0.0            0.0              0.0      0.0           0.0  
1       0.0            0.0              0.0      0.0           0.0  
2       0.0            0.0              0.0      0.0           0.0  
3       0.0            0.0              0.0      0.0           0.0  
4       0.0            0.0              0.0      0.0           0.0  
..      ...            ...              ...      ...           ...  
743     0.0            0.0              0.0      0.0           0.0  
744     0.0            0.0              0.0      0.0           0.0  
745     0.0            0.0              0.0      0.0           0.0  
746     0.0            0.0              0.0      0.0           0.0  
747     0.0            0.0              0.0      0.0           0.0  

[748 rows x 9226 columns]

In [48]:
#Obtain the similarity between every review
# result in a nXn matrix where n is the no. of review
cs_docs=cosine_similarity(df)
cs_docs

array([[1.        , 0.        , 0.00786083, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.00786083, 0.        , 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [49]:
#sorting the document based on similarity score.
ind=(cs_docs[0].argsort()[::-1][0:10])
print("Review which is very close to first review is:",df.index[ind])
df.iloc[ind]

Review which is very close to first review is: Int64Index([0, 637, 70, 473, 703, 119, 610, 630, 660, 187], dtype='int64')


10  10 10  10 grade  10 scale  10 score  10 setting   13  13 film  \
0    0.0    0.0       0.0       0.0       0.0         0.0  0.0      0.0   
637  0.0    0.0       0.0       0.0       0.0         0.0  0.0      0.0   
70   0.0    0.0       0.0       0.0       0.0         0.0  0.0      0.0   
473  0.0    0.0       0.0       0.0       0.0         0.0  0.0      0.0   
703  0.0    0.0       0.0       0.0       0.0         0.0  0.0      0.0   
119  0.0    0.0       0.0       0.0       0.0         0.0  0.0      0.0   
610  0.0    0.0       0.0       0.0       0.0         0.0  0.0      0.0   
630  0.0    0.0       0.0       0.0       0.0         0.0  0.0      0.0   
660  0.0    0.0       0.0       0.0       0.0         0.0  0.0      0.0   
187  0.0    0.0       0.0       0.0       0.0         0.0  0.0      0.0   

     13 rating  15pm  ...  youtube  yun  yun fat  zillion  zillion times  \
0          0.0   0.0  ...      0.0  0.0      0.0      0.0            0.0   
637        0.0   0.0  ...      0.0  0.0      0.0      0.0            0.0   
70         0.0   0.0  ...      0.0  0.0      0.0      0.0            0.0   
473        0.0   0.0  ...      0.0  0.0      0.0      0.0            0.0   
703        0.0   0.0  ...      0.0  0.0      0.0      0.0            0.0   
119        0.0   0.0  ...      0.0  0.0      0.0      0.0            0.0   
610        0.0   0.0  ...      0.0  0.0      0.0      0.0            0.0   
630        0.0   0.0  ...      0.0  0.0      0.0      0.0            0.0   
660        0.0   0.0  ...      0.0  0.0      0.0      0.0            0.0   
187        0.0   0.0  ...      0.0  0.0      0.0      0.0            0.0   

     zombie  zombie movies  zombie students  zombiez  zombiez part  
0       0.0            0.0              0.0      0.0           0.0  
637     0.0            0.0              0.0      0.0           0.0  
70      0.0            0.0              0.0      0.0           0.0  
473     0.0            0.0              0.0      0.0           0.0  
703     0.0            0.0              0.0      0.0           0.0  
119     0.0            0.0              0.0      0.0           0.0  
610     0.0            0.0              0.0      0.0           0.0  
630     0.0            0.0              0.0      0.0           0.0  
660     0.0            0.0              0.0      0.0           0.0  
187     0.0            0.0              0.0      0.0           0.0  

[10 rows x 9226 columns]

<h1><center>END</center></h1>